# Generated by Django 3.2.5 on 2021-11-19 07:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(blank=True, default='N/A', max_length=150)),
                ('displayPage', models.CharField(choices=[('home', 'HomePage'), ('publications', 'OzzyPublications')], default='home', max_length=100)),
                ('description', models.TextField(blank=True, default='N/A', max_length=800)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
