# Generated by Django 3.2.5 on 2021-12-03 17:43

from django.db import migrations, models
import froala_editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('title', models.CharField(blank=True, default='N/A', max_length=150)),
                ('description', froala_editor.fields.FroalaField(default='N/A')),
                ('displayPage', models.CharField(choices=[('home', 'HomePage'), ('publications', 'OzzyPublications'), ('whatisozzy', 'What is Ozzy?'), ('ozzyservices', 'Ozzy Services'), ('samplecases', 'Sample Cases'), ('doctorstestimonial', "Doctor's Testimonial"), ('faq', 'FAQ'), ('contactus', 'Contact Us'), ('none', 'None')], default='home', max_length=100, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OzzyService',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('description', froala_editor.fields.FroalaField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', froala_editor.fields.FroalaField()),
                ('date_posted', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
