# Generated by Django 3.2.5 on 2021-11-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='displayPage',
            field=models.CharField(choices=[('home', 'HomePage'), ('publications', 'OzzyPublications'), ('whatisozzy', 'What is Ozzy?')], default='home', max_length=100),
        ),
    ]
