# Generated by Django 3.2.5 on 2021-11-19 13:32

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_article_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=froala_editor.fields.FroalaField(default='N/A'),
        ),
    ]
