# Generated by Django 3.2.5 on 2021-11-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='displayPage',
            field=models.CharField(choices=[('home', 'HomePage'), ('publications', 'OzzyPublications'), ('whatisozzy', 'What is Ozzy?')], default='home', max_length=100, unique=True),
        ),
    ]
