# Generated by Django 3.2.5 on 2021-11-21 12:57

from django.db import migrations, models
import froala_editor.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='OzzyService',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('description', froala_editor.fields.FroalaField()),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='displayPage',
            field=models.CharField(choices=[('home', 'HomePage'), ('publications', 'OzzyPublications'), ('whatisozzy', 'What is Ozzy?'), ('ozzyservices', 'Ozzy Services'), ('samplecases', 'Sample Cases'), ('doctorstestimonial', "Doctor's Testimonial"), ('faq', 'FAQ'), ('contactus', 'Contact Us'), ('none', 'None')], default='home', max_length=100, unique=True),
        ),
    ]
