# Generated by Django 3.2.5 on 2021-11-25 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', froala_editor.fields.FroalaField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
