# Generated by Django 3.2.5 on 2021-12-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0009_alter_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='lower_steps',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='upper_steps',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
