# Generated by Django 3.2.5 on 2021-11-20 11:52

from django.db import migrations, models
import froala_editor.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
