# Generated by Django 3.2.5 on 2021-11-21 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
    ]
